[package]
name = "megingjord"
version = "1.0.0"
authors = ["Noktoborus <noktoborus@gmail.com>"]
edition = "2021"
license = "MIT"

[dependencies]
renderer = { path = "./broken-osm-renderer" }
indexmap = "*"
tini = "*"
walkers = { git = "https://github.com/noktoborus/walkers.git", branch = "feature" }
futures = "0.3.28"
image = "0.24"
log = "0.4"
egui = "0.24"
egui_extras = { version = "0.24", features = ["svg"] }
eframe = "0.24"
env_logger = "0.10"
geographiclib-rs = "0.2.3"
scanf = "1.2.1"

