name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
         submodules: true

    # basic tests
    - name: Run clippy
      run: cargo clippy --all-features -- -D warnings

    - name: Check rust formatting
      run:  cargo fmt --all --check

    - name: Run tests
      run: cargo test --verbose

    - name: Documentation
      run:  cargo doc

    # Building

    - name: Build
      run: cargo build --verbose


    - name: Install trunk to make wasm32 build
      run: cargo install trunk

    - name: make wasm32 build
      run: trunk build
