name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
         submodules: true

    - name: Install Rust Stable
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        components: clippy
        target: wasm32-unknown-unknown

    # basic tests
    - name: Run clippy
      run: cargo clippy --all-features -- -D warnings

    - name: Check rust formatting
      run:  cargo fmt --all --check

    - name: Run tests
      run: cargo test --verbose

    - name: Documentation
      run:  cargo doc

    # build android
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Setup Android SDK
      uses: android-actions/setup-android@v3

    - name: Install Cargo NDK
      run: cargo install cargo-ndk

    - name: Install Rust Android Target
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
        target: aarch64-linux-android

    - name: Build library for android
      working-directory: ./megingjord-android
      run: cargo ndk --target arm64-v8a -o java/app/src/main/jniLibs/ build --profile release

    - name: Build apk
      working-directory: ./megingjord-android/java
      run: ./gradlew build

    - name: List all files
      run: find

    - name: Archive production artifacts
      uses: actions/upload-artifact@v3
      with:
        name: android-arm64-v8a
        path: |
          megingjord-android/java/app/build/reports/lint-results-debug.html
          **/*.apk

    # build base
    - name: Build
      run: cargo build --verbose

    # build wasm32
    - name: Install trunk to make wasm32 build
      run: cargo install trunk

    - name: make wasm32 build
      run: trunk build

